[package]
name = "war"
version = "0.0.1"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
byteordered = "0.4.0"
failure = "0.1.5"
flate2 = "1.0.11"

[dev-dependencies]
lazy_static = "1.4.0"
lazy-static-include = "2.2.0"

[features]
strict = []
