[package]
name = "war-cli"
version = "0.0.1"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
notify = "4.0.13"
serde_json = "1.0.40"
structopt = "0.3.1"

war = { path = "../war" }

[features]
strict = []
